import { cp, mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';

const root = process.cwd(), out = path.join(root, 'dist'), postsDir = path.join(root, 'posts');
const escape = value => value.replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
const inline = value => escape(value).replace(/`([^`]+)`/g, '<code>$1</code>').replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>').replace(/\*([^*]+)\*/g, '<em>$1</em>').replace(/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/g, '<a href="$2" target="_blank" rel="noreferrer">$1</a>');
const imageSource = value => value.includes('/assets/') ? `../assets/${value.split('/assets/').pop()}` : value;
const parseTags = value => String(value || '').replace(/^\[|\]$/g, '').split(',').map(tag => tag.trim().replace(/^['"]|['"]$/g, '')).filter(Boolean);
const tagMarkup = tags => tags.length ? `<div class="post-tags">${tags.map(tag => `<a class="post-tag" href="../tags/${slugify(tag)}.html">${escape(tag)}</a>`).join('')}</div>` : '';
const postCard = (post, href) => `<article class="post-card">${tagMarkup(post.tags)}<time>${escape(post.date)}</time><h2><a class="post-title" href="${href}">${escape(post.title)}</a></h2><p>${inline(post.description || '')}</p></article>`;
const slugify = value => String(value || '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().trim().replace(/đ/g, 'd').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
function frontMatter(source) { const match = source.match(/^---\s*\n([\s\S]*?)\n---\s*\n?([\s\S]*)$/); if (!match) throw new Error('Mỗi bài cần front matter.'); const data = {}; for (const line of match[1].split('\n')) { const colon = line.indexOf(':'); if (colon > 0) data[line.slice(0, colon).trim()] = line.slice(colon + 1).trim().replace(/^['"]|['"]$/g, ''); } if (!data.title || !data.date) throw new Error('Bài viết cần title và date.'); return { data, content: match[2].trim() }; }
function markdown(source) { const blocks = [], lines = source.split('\n'); for (let i = 0; i < lines.length;) { const line = lines[i].trim(); if (!line) { i++; continue; } const image = line.match(/^!\[([^\]]*)\]\(([^)]+)\)(?:\s*(.*))?$/); if (image) { const caption = image[3]?.trim(); blocks.push(`<figure class="article-image"><img src="${escape(imageSource(image[2]))}" alt="${escape(image[1])}" loading="lazy">${caption ? `<figcaption>${inline(caption)}</figcaption>` : ''}</figure>`); i++; continue; } if (/^>\s?/.test(line)) { const quote = []; while (i < lines.length && /^>\s?/.test(lines[i].trim())) quote.push(lines[i++].trim().replace(/^>\s?/, '')); const quoteContent = quote.map(part => { const quoteImage = part.match(/^!\[([^\]]*)\]\(([^)]+)\)(?:\s*(.*))?$/); return quoteImage ? `<figure class="quote-image"><img src="${escape(imageSource(quoteImage[2]))}" alt="${escape(quoteImage[1])}" loading="lazy">${quoteImage[3]?.trim() ? `<figcaption>${inline(quoteImage[3].trim())}</figcaption>` : ''}</figure>` : inline(part); }).join('<br>'); blocks.push(`<blockquote>${quoteContent}</blockquote>`); continue; } if (/^###\s+/.test(line)) { blocks.push(`<h3>${inline(line.slice(4))}</h3>`); i++; continue; } if (/^#{1,2}\s+/.test(line)) { blocks.push(`<h2>${inline(line.replace(/^#{1,2}\s+/, ''))}</h2>`); i++; continue; } if (/^-\s+/.test(line)) { const items = []; while (i < lines.length && /^-\s+/.test(lines[i].trim())) items.push(`<li>${inline(lines[i++].trim().slice(2))}</li>`); blocks.push(`<ul>${items.join('')}</ul>`); continue; } const p = []; while (i < lines.length && lines[i].trim() && !/^(#{1,3}\s+|-\s+|!\[|>\s?)/.test(lines[i].trim())) p.push(lines[i++].trim()); blocks.push(`<p>${inline(p.join(' '))}</p>`); } return blocks.join('\n'); }
function header(prefix = '') { return `<header class="topbar"><a class="brand" href="${prefix}index.html#trang-chu" aria-label="HỌC THẾ NÀO? Trang chủ"><img class="brand-logo" src="${prefix}assets/images/hocthenao_logo.svg" alt=""><span class="brand-name">HỌC <span>THẾ NÀO?</span></span></a><button class="nav-toggle" aria-label="Mở menu" aria-expanded="false">☰</button><nav aria-label="Điều hướng chính"><a href="${prefix}index.html#trang-chu">Trang chủ</a><a href="${prefix}index.html#lo-trinh">Lộ trình</a><a class="active" href="${prefix}categories/phuong-phap.html">Phương pháp</a><a href="${prefix}categories/giai-tri.html">Giải trí</a><a href="${prefix}index.html#lien-he">Liên hệ</a></nav><a class="header-cta" href="${prefix}index.html#lien-he">Bắt đầu học</a></header>`; }
const footer = '<footer><a class="brand" href="index.html">HỌC <span>THẾ NÀO?</span></a><p>Học đúng cách, sống trọn hành trình.</p><a class="footer-partner" href="https://amthanhnhapkhau.com.vn/danh-muc/phong-hop/thiet-bi-may-tro-giang/" target="_blank" rel="noreferrer">Loa - Micro Trợ Giảng</a><p>© 2026</p></footer>';
const document = (title, content, prefix = '') => `<!doctype html><html lang="vi"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>${escape(title)} | HỌC THẾ NÀO?</title><link rel="icon" type="image/svg+xml" href="${prefix}assets/images/hocthenao_logo.svg"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:wght@400;500;600;700;800&family=Playfair+Display:ital,wght@0,700;0,800;1,700&display=swap" rel="stylesheet"><link rel="stylesheet" href="${prefix}styles.css"><link rel="stylesheet" href="${prefix}posts.css"><link rel="stylesheet" href="${prefix}cards.css"><link rel="stylesheet" href="${prefix}tags.css"><link rel="stylesheet" href="${prefix}quotes.css"><link rel="stylesheet" href="${prefix}images.css"><link rel="stylesheet" href="${prefix}go-top.css"><link rel="stylesheet" href="${prefix}brand.css"><link rel="stylesheet" href="${prefix}brand-header.css"><link rel="stylesheet" href="${prefix}article-headings.css"></head><body>${header(prefix)}<main>${content}</main>${footer}<button class="go-top" type="button" aria-label="Lên đầu trang" title="Lên đầu trang">↑</button><script src="${prefix}script.js"></script></body></html>`;
await rm(out, { recursive: true, force: true }); await mkdir(path.join(out, 'posts'), { recursive: true }); await mkdir(path.join(out, 'categories'), { recursive: true }); await mkdir(path.join(out, 'tags'), { recursive: true });
for (const file of ['index.html', 'styles.css', 'brand.css', 'brand-header.css', 'go-top.css', 'posts.css', 'cards.css', 'tags.css', 'quotes.css', 'images.css', 'article-headings.css', 'script.js', 'CNAME']) await cp(path.join(root, file), path.join(out, file));
await cp(path.join(root, 'assets'), path.join(out, 'assets'), { recursive: true });
const names = (await readdir(postsDir)).filter(name => name.endsWith('.md'));
const posts = await Promise.all(names.map(async filename => { const { data, content } = frontMatter(await readFile(path.join(postsDir, filename), 'utf8')); return { ...data, tags: parseTags(data.tags), category: data.category || '', slug: filename.replace(/\.md$/, ''), html: markdown(content) }; })); posts.sort((a, b) => new Date(b.date) - new Date(a.date));
const cards = posts.length ? posts.map(post => postCard(post, `${post.slug}.html`)).join('') : '<p class="empty">Chưa có bài viết nào.</p>';
await writeFile(path.join(out, 'posts', 'index.html'), document('Bài viết', `<section class="page-hero"><p class="eyebrow">GÓC HỌC TẬP</p><h1>Bài viết mới nhất</h1><p>Những ghi chú ngắn, thực tế để bạn học sâu hơn mỗi ngày.</p></section><section class="post-list">${cards}</section>`, '../'));
const entertainmentPosts = posts.filter(post => slugify(post.category) === 'giai-tri');
const entertainmentCards = entertainmentPosts.length ? entertainmentPosts.map(post => postCard(post, `../posts/${post.slug}.html`)).join('') : '<p class="empty">Chưa có bài viết thuộc danh mục Giải trí. Hãy thêm <code>category: "Giải trí"</code> vào phần đầu bài Markdown để bài xuất hiện ở đây.</p>';
await writeFile(path.join(out, 'categories', 'giai-tri.html'), document('Giải trí', `<section class="page-hero"><p class="eyebrow">DANH MỤC</p><h1>Giải trí</h1><p>Những bài viết nhẹ nhàng, thú vị và truyền cảm hứng.</p></section><section class="post-list">${entertainmentCards}</section>`, '../'));
const methodPosts = posts.filter(post => slugify(post.category) === 'phuong-phap');
const methodCards = methodPosts.length ? methodPosts.map(post => postCard(post, `../posts/${post.slug}.html`)).join('') : '<p class="empty">Chưa có bài viết thuộc danh mục Phương pháp. Hãy thêm <code>category: "Phương pháp"</code> vào phần đầu bài Markdown để bài xuất hiện ở đây.</p>';
await writeFile(path.join(out, 'categories', 'phuong-phap.html'), document('Phương pháp', `<section class="page-hero"><p class="eyebrow">DANH MỤC</p><h1>Phương pháp</h1><p>Những cách học đã được kiểm chứng để hiểu sâu và ghi nhớ lâu.</p></section><section class="post-list">${methodCards}</section>`, '../'));
const tagGroups = new Map();
for (const post of posts) for (const tag of post.tags) { const key = slugify(tag); const group = tagGroups.get(key) || { label: tag, posts: [] }; group.posts.push(post); tagGroups.set(key, group); }
for (const [slug, group] of tagGroups) { const tagCards = group.posts.map(post => postCard(post, `../posts/${post.slug}.html`)).join(''); await writeFile(path.join(out, 'tags', `${slug}.html`), document(group.label, `<section class="page-hero"><p class="eyebrow">THẺ BÀI VIẾT</p><h1>${escape(group.label)}</h1><p>Các bài viết cùng chủ đề.</p></section><section class="post-list">${tagCards}</section>`, '../')); }
for (const post of posts) { const categoryName = post.category || 'Tất cả bài viết'; const categoryHref = post.category ? `../categories/${slugify(post.category)}.html` : 'index.html'; const article = `<article class="article"><a class="back-link" href="${categoryHref}">← ${escape(categoryName)}</a>${tagMarkup(post.tags)}<p class="article-meta">${escape(post.date)}</p><h1>${escape(post.title)}</h1>${post.description ? `<p class="lead">${escape(post.description)}</p>` : ''}<div class="article-content">${post.html}</div></article>`; await writeFile(path.join(out, 'posts', `${post.slug}.html`), document(post.title, article, '../')); }
console.log(`Đã tạo ${posts.length} bài viết.`);
