import { cp, mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';

const root = process.cwd(), out = path.join(root, 'dist'), postsDir = path.join(root, 'posts');
const escape = value => value.replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
const inline = value => escape(value).replace(/`([^`]+)`/g, '<code>$1</code>').replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>').replace(/\*([^*]+)\*/g, '<em>$1</em>').replace(/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/g, '<a href="$2" target="_blank" rel="noreferrer">$1</a>');
const imageSource = value => value.includes('/assets/') ? `../assets/${value.split('/assets/').pop()}` : value;
function frontMatter(source) { const match = source.match(/^---\s*\n([\s\S]*?)\n---\s*\n?([\s\S]*)$/); if (!match) throw new Error('Mỗi bài cần front matter.'); const data = {}; for (const line of match[1].split('\n')) { const colon = line.indexOf(':'); if (colon > 0) data[line.slice(0, colon).trim()] = line.slice(colon + 1).trim().replace(/^['"]|['"]$/g, ''); } if (!data.title || !data.date) throw new Error('Bài viết cần title và date.'); return { data, content: match[2].trim() }; }
function markdown(source) { const blocks = [], lines = source.split('\n'); for (let i = 0; i < lines.length;) { const line = lines[i].trim(); if (!line) { i++; continue; } const image = line.match(/^!\[([^\]]*)\]\(([^)]+)\)(?:\s*(.*))?$/); if (image) { const caption = image[3]?.trim(); blocks.push(`<figure class="article-image"><img src="${escape(imageSource(image[2]))}" alt="${escape(image[1])}" loading="lazy">${caption ? `<figcaption>${inline(caption)}</figcaption>` : ''}</figure>`); i++; continue; } if (/^###\s+/.test(line)) { blocks.push(`<h3>${inline(line.slice(4))}</h3>`); i++; continue; } if (/^#{1,2}\s+/.test(line)) { blocks.push(`<h2>${inline(line.replace(/^#{1,2}\s+/, ''))}</h2>`); i++; continue; } if (/^-\s+/.test(line)) { const items = []; while (i < lines.length && /^-\s+/.test(lines[i].trim())) items.push(`<li>${inline(lines[i++].trim().slice(2))}</li>`); blocks.push(`<ul>${items.join('')}</ul>`); continue; } const p = []; while (i < lines.length && lines[i].trim() && !/^(#{1,3}\s+|-\s+|!\[)/.test(lines[i].trim())) p.push(lines[i++].trim()); blocks.push(`<p>${inline(p.join(' '))}</p>`); } return blocks.join('\n'); }
function header(prefix = '') { return `<header class="topbar"><a class="brand" href="${prefix}index.html#trang-chu" aria-label="HỌC THẾ NÀO? Trang chủ"><img class="brand-logo" src="${prefix}assets/images/hocthenao_logo.svg" alt=""><span class="brand-name">HỌC <span>THẾ NÀO?</span></span></a><button class="nav-toggle" aria-label="Mở menu" aria-expanded="false">☰</button><nav aria-label="Điều hướng chính"><a href="${prefix}index.html#trang-chu">Trang chủ</a><a href="${prefix}index.html#phuong-phap">Phương pháp</a><a href="${prefix}index.html#lo-trinh">Lộ trình</a><a class="active" href="${prefix}posts/">Bài viết</a><a href="${prefix}index.html#lien-he">Liên hệ</a></nav><a class="header-cta" href="${prefix}index.html#lien-he">Bắt đầu học</a></header>`; }
const footer = '<footer><a class="brand" href="index.html">HỌC <span>THẾ NÀO?</span></a><p>Học đúng cách, sống trọn hành trình.</p><a class="footer-partner" href="https://amthanhnhapkhau.com.vn/danh-muc/phong-hop/thiet-bi-may-tro-giang/" target="_blank" rel="noreferrer">Loa - Micro Trợ Giảng</a><p>© 2026</p></footer>';
const document = (title, content, prefix = '') => `<!doctype html><html lang="vi"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>${escape(title)} | HỌC THẾ NÀO?</title><link rel="icon" type="image/svg+xml" href="${prefix}assets/images/hocthenao_logo.svg"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:wght@400;500;600;700;800&family=Playfair+Display:ital,wght@0,700;0,800;1,700&display=swap" rel="stylesheet"><link rel="stylesheet" href="${prefix}styles.css"><link rel="stylesheet" href="${prefix}posts.css"><link rel="stylesheet" href="${prefix}images.css"><link rel="stylesheet" href="${prefix}go-top.css"><link rel="stylesheet" href="${prefix}brand.css"><link rel="stylesheet" href="${prefix}brand-header.css"></head><body>${header(prefix)}<main>${content}</main>${footer}<button class="go-top" type="button" aria-label="Lên đầu trang" title="Lên đầu trang">↑</button><script src="${prefix}script.js"></script></body></html>`;
await rm(out, { recursive: true, force: true }); await mkdir(path.join(out, 'posts'), { recursive: true });
for (const file of ['index.html', 'styles.css', 'brand.css', 'brand-header.css', 'go-top.css', 'posts.css', 'images.css', 'script.js', 'CNAME']) await cp(path.join(root, file), path.join(out, file));
await cp(path.join(root, 'assets'), path.join(out, 'assets'), { recursive: true });
const names = (await readdir(postsDir)).filter(name => name.endsWith('.md'));
const posts = await Promise.all(names.map(async filename => { const { data, content } = frontMatter(await readFile(path.join(postsDir, filename), 'utf8')); return { ...data, slug: filename.replace(/\.md$/, ''), html: markdown(content) }; })); posts.sort((a, b) => new Date(b.date) - new Date(a.date));
const cards = posts.length ? posts.map(post => `<a class="post-card" href="${post.slug}.html"><time>${escape(post.date)}</time><h2>${escape(post.title)}</h2><p>${inline(post.description || '')}</p></a>`).join('') : '<p class="empty">Chưa có bài viết nào.</p>';
await writeFile(path.join(out, 'posts', 'index.html'), document('Bài viết', `<section class="page-hero"><p class="eyebrow">GÓC HỌC TẬP</p><h1>Bài viết mới nhất</h1><p>Những ghi chú ngắn, thực tế để bạn học sâu hơn mỗi ngày.</p></section><section class="post-list">${cards}</section>`, '../'));
for (const post of posts) { const article = `<article class="article"><a class="back-link" href="index.html">← Tất cả bài viết</a><p class="article-meta">${escape(post.date)}</p><h1>${escape(post.title)}</h1>${post.description ? `<p class="lead">${escape(post.description)}</p>` : ''}<div class="article-content">${post.html}</div></article>`; await writeFile(path.join(out, 'posts', `${post.slug}.html`), document(post.title, article, '../')); }
console.log(`Đã tạo ${posts.length} bài viết.`);
